services:
    keycloak:
        depends_on:
            - postgres
        container_name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        command: start-dev
        environment:
            KC_HTTP_PORT: 8081
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KC_DB: postgres
            KC_DB_URL_HOST: postgres
            KC_DB_URL_DATABASE: ${POSTGRESQL_DB_NAME}
            KC_DB_SCHEMA: keycloak
            KC_DB_USERNAME: ${POSTGRESQL_USER}
            KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
        networks:
            - web

    postgres:
        container_name: postgres
        image: postgres:17
        environment:
            POSTGRES_DB: ${POSTGRESQL_DB_NAME}
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./sql/init:/docker-entrypoint-initdb.d
        networks:
            - web

    redis:
        container_name: redis
        image: redis:7.2
        command: >
            redis-server
            --user ${REDIS_USER} on ">${REDIS_PASSWORD}" ~* +@all
            --user default off
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - web

volumes:
    postgres-data:
        name: postres-data
    redis-data:
        name: redis-data

networks:
    web:
        driver: bridge
