services:
    keycloak:
        depends_on:
            - postgres
        image: quay.io/keycloak/keycloak:24.0.1
        container_name: keycloak
        command: start-dev
        environment:
            KC_HTTP_PORT: 8081
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KC_DB: postgres
            KC_DB_URL_HOST: postgres
            KC_DB_URL_DATABASE: ${POSTGRESQL_DB_NAME}
            KC_DB_SCHEMA: keycloak
            KC_DB_USERNAME: ${POSTGRESQL_USER}
            KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
        networks:
            - web

    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: ${POSTGRESQL_DB_NAME}
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./sql/init:/docker-entrypoint-initdb.d
        networks:
            - web

    redis:
        image: redis:7
        networks:
            - web

volumes:
    ssl-storage:
        name: ssl-storage
    postgres-data:
        name: postres-data

networks:
    web:
        driver: bridge
