spring:
    application:
        name: my-api
    datasource:
        url: jdbc:postgresql://postgres:5432/${POSTGRESQL_DB_NAME}
        username: ${POSTGRESQL_USER}
        password: ${POSTGRESQL_PASSWORD}
    cache:
        type: redis
    redis:
        host: redis
        port: 6379

server:
    port: 8080

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG

springdoc:
    swagger-ui:
        path: /api/swagger-ui.html
    api-docs:
        path: /api/v3/api-docs

jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            default_schema: my-api


management:
    endpoints:
        web:
            exposure:
                include:
                    - health
                    - info
